FROM golang:1.23 AS build 

WORKDIR /app

COPY . .

RUN go mod tidy 

RUN go build -ldflags="-w -s" -o app main.go

FROM alpine:latest 

WORKDIR /app

COPY --from=build /app/app .

ENTRYPOINT [ "./app" ]

